@baseUrlUser = http://localhost:3000
@baseUrlUrl = http://localhost:3001
@authToken = {{authenticate.response.body.token}}

# @name list-users
GET {{baseUrlUser}}/user
Authorization: {{authToken}}

###

# @name create-user
POST {{baseUrlUser}}/user
Content-Type: application/json

{
  "name": "",
  "email": "marcus@email.com",
  "password": "123456"
}

###

# @name authenticate
POST {{baseUrlUser}}/auth
Content-Type: application/json

{
  "email": "daniel@email.com",
  "password": "123456"
}

###

GET {{baseUrlUrl}}/url

###

POST {{baseUrlUrl}}/url
Content-Type: application/json

{
  "original": "daniel",
  "short": "http://3f5g7h"
}