@baseUrlUser = http://localhost:3000
@baseUrlUrl = http://localhost:3001
@authToken = {{authenticate.response.body.token}}

# @name list-users
GET {{baseUrlUser}}/users
Authorization: {{authToken}}

###
# @name list-urls
GET {{baseUrlUrl}}/urls
Authorization: {{authToken}}

###
# @name create-user
POST {{baseUrlUser}}/users
Content-Type: application/json

{
  "name": "Marcus",
  "email": "marcus@email.com",
  "password": "123456"
}

###

# @name create-url

POST {{baseUrlUrl}}/urls
Content-Type: application/json
Authorization: {{authToken}}

{
  "url_original": "https://www.alura.com"
}

###

# @name authenticate
POST {{baseUrlUser}}/auth
Content-Type: application/json

{
  "email": "marcus@email.com",
  "password": "123456"
}


###
GET {{baseUrlUrl}}/urls/ont3jo

###
GET {{baseUrlUrl}}/urls

###
POST {{baseUrlUrl}}/urls
Content-Type: application/json
Authorization: {{authToken}}

{
  "url_original": "https://www.mercadolivre.com.br"
}

###
# @name Delete-Url
DELETE {{baseUrlUrl}}/urls/a983de4b-6aca-4146-a4f9-20a5bf234bb4
Authorization: {{authToken}}

###

# @name Update-Url
PUT {{baseUrlUrl}}/urls/dc2304ed-1b5f-4b4c-b989-ce349b1e0718
Authorization: {{authToken}}

{
  "url_original": "https://www.netflix.com"
}


