@baseUrlUser = http://localhost:3000
@baseUrlUrl = http://localhost:3001
@authToken = {{authenticate.response.body.token}}

# @name list-users
GET {{baseUrlUser}}/users
Authorization: {{authToken}}

###
# @name list-urls
GET {{baseUrlUrl}}/urls

###
# @name create-user
POST {{baseUrlUser}}/users
Content-Type: application/json

{
  "name": "Daniel",
  "email": "daniel@email.com",
  "password": "123456"
}

###

# @name create-url

POST {{baseUrlUrl}}/urls
Content-Type: application/json
Authorization: {{authToken}}

{
  "original": "https://mercadolivre.com.br"
}

###

# @name authenticate
POST {{baseUrlUser}}/auth
Content-Type: application/json

{
  "email": "daniel@email.com",
  "password": "123456"
}


###
GET {{baseUrlUrl}}/urls/ont3jo

###
GET {{baseUrlUrl}}/urls

###
POST {{baseUrlUrl}}/urls
Content-Type: application/json
Authorization: {{authToken}}

{
  "original": "https://www.alura.com.br"
}

###
# @name Delete-Url
DELETE {{baseUrlUrl}}/urls
Authorization: {{authToken}}

###
# @name Update-Url
PUT {{baseUrlUrl}}/urls



